### PR TITLE
application: initial exploration into top level module

### PR DESCRIPTION
**Pull request by elf-pavlik**
i'm creating new package not to mess around with current client package.
relevant changes only in application and data-model packages.

### CODE REVIEW

**Comment by angel-araya-jd** [comment]
Hey @elf-pavlik - I like most of what I see.

My only question is if you plan on adding the properties of a data type as member of the classes, i.e.:
```typescript
export class AccessReceipt extends Model {

  public readonly registeredBy: IRI;
  public readonly registeredWith: IRI;
  // Add the other as needed...

  private constructor(iri: string, factory) {
     super(iri, factory);
     const properties = parseAccessReceipt(this.dataset);
     this.registeredBy = properties.registeredBy;
     this.registeredWith = properties.registeredWith;
     // .. set the rest as needed
     // This would require moving the `.fetchData` call to before the constructor or some other trivial workaround.
  }

  public static async build(iri: string, factory: InteropFactory): Promise<AccessReceipt> {
    const instance = new AccessReceipt(iri, factory);
    await instance.fetchData();
    return instance;
  }
}
```
... or, do you plan on settting this properties in a different way?

**Comment by elf-pavlik** [comment]
Most models have `private async bootstrap()` called by `public static build()` it usually calls `this.fetchData()` first and after that we have already have`this.dataset` available. For now I've been only defining properties for I needed to use, pretty much to make my way to Data Registration and Data Instance.

Once I have that I will start adding async iterators which can be forwarded and aggregated. Those possibly will be attached to each Data Registration, even though they will use different traversal to get at the related Data Instances depending on scope of the Data Grant. I plan to have some of it ready and pushed as part of this draft before our call on Wednesday.

**Comment by elf-pavlik** [comment]
Tomorrow I plan to wrap up work on https://github.com/elf-pavlik/sai-js/tree/forwarding-grant-details, since it iterates on some work here I will probably add it directly to this PR.

**Review by angel-araya-jd — APPROVED** [review]
LGTM!

**Pull request merged**
